# Generated by Django 5.2.6 on 2025-09-30 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otp',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
